* Repositorium

Web Engine for Collective Repositories. Based principally on CakePHP and MySQL

Originally a Project for "CC5401 - Ingenieria de software" course of DCC UChile.

* Installation
** Requirements
   
   + MySQL >= 5.1 
   + PHP >= 5.3
   + Apache >= 2.2 


** Getting the source

*** Option 1. Using git

Open a console and get the source

=git clone git://github.com/mquezadav/repositorium.git=

*** Option 2. Using the given cd (professors and client)

The cd contains all the necessary files to use the application.

** Configuration


Then you’ll have a copy of the sources at local. Now you have to give permissions to some folders to get cake working properly:
Una vez que se tiene una copia del repo en local, hay que darle permisos a ciertas carpetas para que cake funcione correctamente:


- =chmod o+w /app/tmp=
- =chmod o+w /app/tmp/cache=
- =chmod -R o+w /app/tmp/cache/persistent=
- =chmod -R o+w /app/tmp/cache/models=
- =chmod -R o+w /app/tmp/logs=


Edit =database.php= at =~/app/config=  at line 76 
        var $default = array(
                'driver' => 'mysql',
                'persistent' => false,
                'host' => '<HOST>',
                'login' => '<LOGIN>',
                'password' => '<PASSWORD>',
                'database' => '<DBNAME>',
                'prefix' => '',
       );


Change =<HOST>=, =<LOGIN>=, =<PASSWORD>= and =<DBNAME>= (database name) to the correspoding values in your system

** Initial DB Dump

1) To load the dump file (=bootstrap.sql=) with initial data (users: admin and anonymous). It contains no documents and no criteria. 

   =mysql -u <LOGIN> -p <PASSWORD> <DBNAME> < bootstrap.sql=

2) Now you have 2 users: anonymous and admin. The *admin* user has the following atributes
    - Login: admin@example.com
    - Password: password

3) Then add a criteria, and then some documents or users.

4) If you want to see a demo of the application, load =bootstrap_demo.sql=, it contains some documents, criteria and statistics

** Security 
/Read only if you want to have mutiple copies of Repositorium running on the same machine/

At =core.php= file (=~/app/config/=), at lines 204 and 209, randomly modify some alphanumeric characters of the corresponding Salt and Cypher Seed. Those characters have to be replaced not addded (it would enlarge the string)
Configure::write('Security.salt', 'HA87fmO43HdcmUD02nchqa*UN*dlbmqtycpkcbdy462nGV*kcm*2Gu'); -->  Configure::write('Security.salt', 'HA87fmO43HdcmUD02nchqa*16*dlbmqtycpkcbdy462nGVl*402*Gu');

This changes’ll avoid keeping the same session at different app clones.


* Staff
1. Jérémy "LeJyBy" Barbay (our project client) 
2. Hernan Fierro (project administrator) 
3. Pablo Estefo - pestefo (analyst) 
4. Felipe Banados - fbanados (designer) 
5. Nicolas Perez - thomaslight (developer) 
6. Mauricio Quezada - mquezadav (developer) 
7. David Contreras - dcontrer (tester)

