* Repositorium

Problem repository database application. Web Application based principally on CakePHP and MySQL.

It was a project for "CC5401 - Ingenieria de software" course of DCC UChile, but now in active development.

* Installation
** Requirements
   
   + MySQL 5.1 
   + PHP 5.3 (any php5 should work fine too)
   + Apache 2.2 


** Getting the source

Open a console and get the source

=git clone git://github.com/mquezadav/repositorium.git=

** Configuration

Then you’ll have a copy of the source at local. 

Create the following folders and give these permissions (some of them
already exist):

- =chmod o+w app/tmp=
- =chmod o+w app/tmp/cache=
- =chmod -R o+w app/tmp/cache/persistent=
- =chmod -R o+w app/tmp/cache/models=
- =chmod -R o+w app/tmp/logs=


Copy =database.php.default= to =database.php=, and =core.php.default= 
to =core.php=, and =bootstrap.php.default= to =bootstrap.php= in =app/config=. 

Edit =database.php= at line 76 
        ~var $default = array('driver' => 'mysql','persistent' => false,'host' => '<HOST>','login' => '<LOGIN>','password' => '<PASSWORD>','database' => '<DBNAME>','prefix' => '',);~
Change =<HOST>=, =<LOGIN>=, =<PASSWORD>= and =<DBNAME>= (database name) to the correspoding values in your system

** Initial DB Dump

1) To load the dump file (=repositorium.sql=) with initial data (users: admin and anonymous). It contains no documents and no criteria. 

   =mysql -u <LOGIN> -p <PASSWORD> <DBNAME> < repositorium.sql=

2) Now you have 2 users: anonymous and admin. The *admin* user has the following atributes
    - Login: admin@example.com
    - Password: password

3) Then add a criteria, and then some documents or users.

** Security

At =core.php= file (=~/app/config/=), at lines 204 and 209, randomly modify some alphanumeric characters of the corresponding Salt and Cypher Seed. 
Example:

=Configure::write('Security.salt', '<SOME LONG RANDOM STRING>');=

This changes’ll avoid keeping the same session at different app clones, and for security sake.


* Credits
1. Jérémy Barbay - jyby (our course client) 
2. Hernan Fierro (project manager) 
3. Pablo Estefo - pestefo (analyst) 
4. Felipe Banados - fbanados (designer) 
5. Nicolas Perez - thomaslight (developer) 
6. Mauricio Quezada - mquezadav (developer) 
7. David Contreras - dcontrer (tester)

